#pragma once

#include "binaryTree.h"
#include "MaxHeap.h"
#include "BinarySearchTree.h"
#include "arraryList.h"
#include "AVLTree.h"
#include "generateHelper.h"
#include "BTree.h"
#include "graph.h"
#include "RedBlackTree.h"
#include "RankSort.h"
#include "QuickSort.h"
#include "linkedList.h"
#include "MergeSort.h"
#include "InsertionSort.h"
#include "ShellSort.h"